p8105_hw3_iah2124
================
Iris Hart
2024-10-10

# Problem 1

### Loading packages + data

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.1     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.3     ✔ tidyr     1.3.1
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(ggplot2)
library(readr)

library(p8105.datasets)
data("ny_noaa")
```

There are 7 variables and 2,595,176 observations in the NY NOAA data
set. The variables are Weather station ID, observation date,
precipitation (tenths of mm), snowfall (mm), snow depth (mm),
temperature max and temperature min (in tenths of degrees C).

Create year, month, and day variables and convert precipitation variable
to be mm instead of tenths of mm. Convert daily temperature min and max
variables to be degrees to be degrees Celsius from tenths of degrees
Celsius.

``` r
library(dplyr)
library(lubridate)

ny_noaa_clean <- ny_noaa %>%
  mutate(
    year = year(date),              
    month = month(date),            
    day = day(date),               
    tmax = as.numeric(tmax) / 10,   
    tmin = as.numeric(tmin) / 10,   
    prcp = as.numeric(prcp) / 100,  
    snow = as.numeric(snow) / 10    
  )
```

View to make sure new variables are created and changes were made

``` r
view(ny_noaa_clean)
```

### Snowfall analysis: most commonly observed values

``` r
snowfall_counts = ny_noaa_clean %>%
  count(snow) %>%
  arrange(desc(n))  

head(snowfall_counts)
```

    ## # A tibble: 6 × 2
    ##    snow       n
    ##   <dbl>   <int>
    ## 1   0   2008508
    ## 2  NA    381221
    ## 3   2.5   31022
    ## 4   1.3   23095
    ## 5   5.1   18274
    ## 6   7.6   10173

The most commonly observed day by far was 0cm, for 2,008,508 times. This
makes sense because most days in NY do not have snow, there are only a
few days a year that it does snow. The next most common observation was
NA (n = 381,221), which also makes sense since missing data is common.
The next most common snowfall amounts were 2.5cm(n = 31,022) and 1.3cm(n
= 23,095). These amounts are pretty small but it doesn’t typically snow
too much when it does snow so this also would be common amounts. The
last two most common snowfall amounts are 5.1cm(n = 18,274) and 7.6cm(n
= 10,173). These amounts are a bit larger than the last two but still
not a huge amount of snow.

### Create a two-panel plot of average max temperature in Jan and July

``` r
ny_noaa = 
  ny_noaa %>% 
  separate(date, into = c("year", "month", "day"), convert = TRUE) %>% 
  mutate(
    tmax = as.numeric(tmax),
    tmin = as.numeric(tmin))
```

``` r
ny_noaa %>% 
  group_by(id, year, month) %>% 
  filter(month %in% c(1, 7)) %>% 
  summarize(mean_tmax = mean(tmax, na.rm = TRUE, color = id)) %>% 
  ggplot(aes(x = year, y = mean_tmax, group = id)) + geom_point() + geom_path() +
  facet_grid(~month) +
  labs(title = "Mean monthly temperature for each station across years for January and July")
```

    ## `summarise()` has grouped output by 'id', 'year'. You can override using the
    ## `.groups` argument.

    ## Warning: Removed 5970 rows containing missing values or values outside the scale range
    ## (`geom_point()`).

    ## Warning: Removed 5931 rows containing missing values or values outside the scale range
    ## (`geom_path()`).

![](p8105_hw3_iah2124_files/figure-gfm/unnamed-chunk-6-1.png)<!-- -->
